# name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - develop

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build Docker Image
#       run: docker build -t lhourquin/training-book:latest .

#     - name: Push Docker Image
#       run: docker push lhourquin/training-book:latest
